name: Run Unit Test via Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install uv
          uv venv
          uv pip install -e .[dev]
      - name: Lint with Ruff
        run: |
          uv run ruff check --target-version=py310 .
        continue-on-error: true
      - name: Test with pytest
        run: |
          uv run pytest --cov emcfile -xs .
      - name: Generate Coverage Report
        run: |
          uv run coverage report -m
